// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlc

import (
	"context"
	"time"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (title, description, filename, uploaded_at) 
VALUES (?, ?, ?, ?) 
RETURNING filename, title, description, uploaded_at
`

type CreateVideoParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Filename    string    `json:"filename"`
	UploadedAt  time.Time `json:"uploaded_at"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.Title,
		arg.Description,
		arg.Filename,
		arg.UploadedAt,
	)
	var i Video
	err := row.Scan(
		&i.Filename,
		&i.Title,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos 
WHERE title = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, title string) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, title)
	return err
}

const getVideosByTitle = `-- name: GetVideosByTitle :many
SELECT filename, title, description, uploaded_at FROM videos 
WHERE title LIKE ?
`

func (q *Queries) GetVideosByTitle(ctx context.Context, title string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideosByTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.Filename,
			&i.Title,
			&i.Description,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
