// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Video struct {
	ID          string
	Title       string
	Description string
	Extension   string
	Duration    int64
	Views       int64
	UploadedAt  time.Time
}
