// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Video struct {
	Filename    string
	Extension   string
	Title       string
	Description string
	UploadedAt  time.Time
}
