// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, id string) error
	GetVideo(ctx context.Context, id string) (Video, error)
	ListVideos(ctx context.Context) ([]Video, error)
	UpdateVideoMetadata(ctx context.Context, arg UpdateVideoMetadataParams) error
}

var _ Querier = (*Queries)(nil)
