// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlc

import (
	"context"
	"time"
)

const countVideos = `-- name: CountVideos :one
SELECT COUNT(*) FROM videos
`

func (q *Queries) CountVideos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, title, description, extension, duration, uploaded_at)
VALUES (?, ?, ?, ?, ?, ?) 
RETURNING id, title, description, extension, duration, views, uploaded_at
`

type CreateVideoParams struct {
	ID          string
	Title       string
	Description string
	Extension   string
	Duration    int64
	UploadedAt  time.Time
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Extension,
		arg.Duration,
		arg.UploadedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Extension,
		&i.Duration,
		&i.Views,
		&i.UploadedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos
WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, id)
	return err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, description, extension, duration, views, uploaded_at FROM videos 
WHERE id = ?
`

func (q *Queries) GetVideo(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Extension,
		&i.Duration,
		&i.Views,
		&i.UploadedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, description, extension, duration, views, uploaded_at FROM videos
ORDER BY uploaded_at DESC
LIMIT ? OFFSET ?
`

type ListVideosParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Extension,
			&i.Duration,
			&i.Views,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoMetadata = `-- name: UpdateVideoMetadata :exec
UPDATE videos
SET duration = ?
WHERE id = ?
`

type UpdateVideoMetadataParams struct {
	Duration int64
	ID       string
}

func (q *Queries) UpdateVideoMetadata(ctx context.Context, arg UpdateVideoMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoMetadata, arg.Duration, arg.ID)
	return err
}
