// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlc

import (
	"context"
	"time"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (title, description, filename, extension, uploaded_at) 
VALUES (?, ?, ?, ?, ?) 
RETURNING filename, extension, title, description, uploaded_at
`

type CreateVideoParams struct {
	Title       string
	Description string
	Filename    string
	Extension   string
	UploadedAt  time.Time
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.Title,
		arg.Description,
		arg.Filename,
		arg.Extension,
		arg.UploadedAt,
	)
	var i Video
	err := row.Scan(
		&i.Filename,
		&i.Extension,
		&i.Title,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos 
WHERE title = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, title string) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, title)
	return err
}

const getVideo = `-- name: GetVideo :one
SELECT filename, extension, title, description, uploaded_at FROM videos 
WHERE filename = ?
`

func (q *Queries) GetVideo(ctx context.Context, filename string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, filename)
	var i Video
	err := row.Scan(
		&i.Filename,
		&i.Extension,
		&i.Title,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT filename, extension, title, description, uploaded_at FROM videos
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.Filename,
			&i.Extension,
			&i.Title,
			&i.Description,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
